[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "app"
version = "0.1.0"
description = ""
dependencies = [
  "autopep8>=2.0.4",
]

[project.scripts]
cli = "app.cli:main"

[tool.setuptools.packages.find]
include = ["app*"]
